# Generated by Django 2.2.5 on 2019-09-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='time')),
                ('origin', models.CharField(max_length=150, verbose_name='origin')),
                ('destination', models.CharField(max_length=150, verbose_name='destination')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('seats', models.IntegerField(verbose_name='seats')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='price')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
        ),
    ]
